---
version: 1
datastore:
  filename: stats.json
scheduler:
  interval: 5
eventstores:
  track_locations:
    url: http://storage:8090/track/locations
  track_alerts:
    url: http://storage:8090/track/alerts